### ISSUE TITLE
recommendation to avoid problems with jQuery 1.11.3...

### ISSUE THREAD

**Issue by hbriceno** [englercj/jquery-ajax-progress#4]
Hello,
I have seen a similar approach to yours for doing the progress bar.
I found a bug that would appear only on IE11 Win7 (probably Win8, not Win10)
The issue is around this code:

```
var oldXHR = $.ajaxSettings.xhr;
$.ajaxSettings.xhr = function() {
    var xhr = oldXHR();
```

the problem is that the oldXHR seems to be getting the wrong "this"... in jQuery 1.11.3 it relies on this.type, so the fix I would suggest is to change the code above with:

```
var oldXHR = $.ajaxSettings.xhr;
$.ajaxSettings.xhr = function() {
    var that = this;
    var xhr = oldXHR.bind(that)();
```

**Comment by englercj** [comment]
probably want to do `oldXHR.call(this);` instead.
